# Generated by Django 4.0.5 on 2022-06-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accountid',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='post',
            name='showblog',
            field=models.IntegerField(max_length=1),
        ),
    ]
