# Generated by Django 4.0.5 on 2022-06-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_accountid_alter_post_showblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('text_content', models.CharField(max_length=1020)),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
                ('show_comment', models.IntegerField(max_length=1)),
            ],
        ),
    ]
