# Generated by Django 4.0.5 on 2022-06-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_cate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
